---
# Ubuntu 20.04/18.04/16.04
# apt install will create 【postgres】 user of Linux and administrator user of PostgreSQL

- name: Add PostgreSQL repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add PostgreSQL repository 
  apt_repository:
    repo: 'deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main'
    filename: pgdg

- name: Install PostgreSQL {{postgresql_version}}
  apt:  
    name: postgresql-{{postgresql_version}}
    
- name: Change postgresql databases METHOD
  lineinfile:
      dest: /etc/postgresql/{{postgresql_version}}/main/pg_hba.conf
      regexp: 'host    all             all             127.0.0.1/32            ident'
      line: "host    all             all             127.0.0.1/32            md5"
      state: present
      
- block:
  - name: enable PostgrepSQL Remote connection by modify postgresql.conf
    lineinfile:
      dest: /etc/postgresql/{{postgresql_version}}/main/postgresql.conf
      regexp: "#listen_addresses = 'localhost'"
      line: "listen_addresses = '*'"
      state: present

  - name: enable PostgrepSQL Remote connection by modify pg_hba.conf
    lineinfile:
      dest: /etc/postgresql/{{postgresql_version}}/main/pg_hba.conf
      line: "host    all             all             0.0.0.0/0            md5"
  when: postgresql_remote

- name: Restart PostgreSQL Service
  service: name=postgresql@{{postgresql_version}}-main.service state=restarted enabled=yes

- name: Change postgresql password
  become: yes
  become_user: postgres
  postgresql_user:
    name: postgres
    password: '{{postgresql_password}}'
    
- name: Create soft link of PostgreSQL
  shell: |
    ln -sf /var/lib/postgresql/{{postgresql_version}} /data/postgresql/data
    ln -sf /etc/postgresql/{{postgresql_version}} /data/postgresql/config
    ln -sf /etc/postgresql/{{postgresql_version}}/main/postgresql.conf /data/postgresql
    ln -sf /data/postgresql/config /data/config/postgresql
    ln -sf /var/log/postgresql /data/logs
